[General]
allowMultipleGuiInstances=true
checkForUpdates=false
contrastOpacity=188
contrastUiColor=#142ef2
copyAndCloseAfterUpload=true
disabledTrayIcon=true
saveAsFileExtension=png
savePath=/home/lambillda/Pictures/flameshot
savePathFixed=true
showDesktopNotification=false
showHelp=false
showStartupLaunchMessage=false
startupLaunch=true
uiColor=#00ff9c
